before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
  - build
  - test
  - coverage
  - deploy
#  - test-deployment

build:
  tags:
    - robot
  stage: build
  script: docker build -f ./gradle-skeleton/Dockerfile --build-arg LOCAL_USER_ID=`id -u`  --tag citest ./gradle-skeleton

test:
  tags:
    - robot
  stage: test
  script: gradle-skeleton/scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage
  coverage: '/TOTAL COVERAGE: \d+\%/'


pages:
  stage: coverage
  tags:
    - robot
  dependencies:
    - test
  script:
    - mv coverage public/
  artifacts:
    paths:
      - public

deploy:
  tags:
    - robot
  stage: deploy
  script: ./gradle-skeleton/scripts/redeploy.sh

#test-deployment:
#  tags:
#    - ece651
#  stage: test-deployment
#  dependencies:
#    - deploy
#  script: ./gradle-skeleton/scripts/test-deployment.sh
