/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team8.server;

import edu.duke.ece651.team8.shared.*;

import java.io.IOException;
import java.util.ArrayList;
import java.io.BufferedReader;
import java.io.InputStreamReader;
public class App {
    /**
     * This main method runs the server, listening on port 1651.
     * Specifically, it creates an instance and calls run.
     * When done from the command line, this program runs until
     * externally killed??
     * @param args is the command line arguments.  These are currently ignored.
     * @throws IOException if creation of the ServerSocket fails.
    */
    public static void main(String[] args) throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        int num=0;
        while(num<2 || num>4) {
            System.out.println("Enter player number (between 2~4): ");
            String line = reader.readLine();
            try{num = Integer.parseInt(line);}
            catch(NumberFormatException e){num=0;}
        }
        System.out.println("Can now start connecting clients.");
        AbstractMapFactory factory = new V1MapFactory();
        Server server = new Server(8080, num, factory);
        server.run();
    }
}

