/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team8.shared;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

class AppTest {
  /*
  @Test
  void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        }*/
}
